include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_redundant_argument_values: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    prefer_single_quotes: true
    unnecessary_lambdas: true
